import React, { useState } from 'react';
import Icon from '../components/Icon.js';
import { Button, Card, Modal, Pill } from '../components/UI.js';
import { Header } from '../components/Shell.js';
export default function ClinicalWorkspace({ t, lang, setLang, theme, setTheme, navigate, notify }) {
    const [tab, setTab] = useState('summary');
    const [complete, setComplete] = useState(false);
    const tabs = [['summary', 'ملخص الزيارة', 'Summary'], ['complaint', 'الشكوى', 'Chief complaint'], ['exam', 'الفحص', 'Examination'], ['diagnosis', 'التشخيص', 'Diagnosis'], ['orders', 'الأوامر والوصفات', 'Orders & Rx'], ['plan', 'خطة العلاج', 'Treatment plan'], ['followup', 'المتابعة', 'Follow-up']];
    return React.createElement("div", { className: "page-enter" },
        React.createElement(Header, { title: t('مساحة الزيارة', 'Visit Workspace'), subtitle: `${t('أحمد مصطفى', 'Ahmed Mostafa')} · V-009821 · ${t('بدأت 10:18', 'Started 10:18')}`, action: React.createElement(Button, { onClick: () => setComplete(true) }, t('إكمال الزيارة', 'Complete visit')), lang: lang, setLang: setLang, theme: theme, setTheme: setTheme, navigate: navigate, t: t }),
        React.createElement("div", { className: "clinical-alert" },
            React.createElement(Icon, { name: "alert" }),
            React.createElement("div", null,
                React.createElement("strong", null, t('حساسية بنسلين', 'Penicillin allergy')),
                React.createElement("span", null, t('تنبيه مسجل بواسطة الطبيب — النظام لا يستنتج قراراً طبياً.', 'Clinician-entered warning — the system makes no autonomous medical decision.')))),
        React.createElement("div", { className: "clinical-grid" },
            React.createElement(Card, { className: "clinical-nav" },
                React.createElement("span", { className: "section-eyebrow" }, t('توثيق الزيارة', 'Visit documentation')),
                tabs.map(([id, ar, en], i) => React.createElement("button", { key: id, className: tab === id ? 'active' : '', onClick: () => setTab(id) },
                    React.createElement("span", null, i + 1),
                    t(ar, en),
                    id === 'summary' && React.createElement(Pill, { tone: "warn" }, t('مسودة', 'Draft'))))),
            React.createElement(Card, { className: "clinical-editor pad-20" },
                React.createElement("div", { className: "section-title" },
                    React.createElement("div", null,
                        React.createElement("h3", null, t(...tabs.find(x => x[0] === tab).slice(1))),
                        React.createElement("p", null, t('الحفظ التلقائي يحافظ على النص، والحفظ اليدوي متاح بوضوح.', 'Autosave preserves text; explicit manual save remains available.'))),
                    tab === 'orders' && React.createElement(Button, { icon: "plus", onClick: () => notify(t('تم فتح أمر سريري جديد', 'New clinical order opened')) }, t('أمر جديد', 'New order'))),
                tab === 'summary' ? React.createElement("div", { className: "definition-grid" }, [[t('سبب الزيارة', 'Reason'), t('متابعة ضغط الدم', 'Blood pressure follow-up')], [t('آخر قياسات', 'Latest vitals'), 'BP 145/92 · Pulse 82'], [t('التشخيص الحالي', 'Current diagnosis'), t('ارتفاع ضغط الدم', 'Hypertension')], [t('المتابعة', 'Follow-up'), t('بعد أسبوعين', 'In 2 weeks')]].map(([a, b]) => React.createElement("div", { className: "definition", key: a },
                    React.createElement("span", null, a),
                    React.createElement("strong", null, b)))) : tab === 'orders' ? React.createElement("div", { className: "history-stack" }, ['Amlodipine 5mg · Active', 'HbA1c · Requested'].map(x => React.createElement("div", { className: "history-row", key: x },
                    React.createElement("span", { dir: "ltr" }, x),
                    React.createElement(Button, { variant: "ghost", icon: "edit" }, t('تعديل', 'Edit'))))) : React.createElement("textarea", { className: "clinical-textarea", placeholder: t('اكتب ملاحظات الطبيب هنا…', 'Enter clinician notes here…') }),
                React.createElement("div", { className: "editor-footer" },
                    React.createElement("span", null,
                        React.createElement("span", { className: "save-dot" }),
                        t('تم الحفظ منذ لحظات', 'Saved moments ago')),
                    React.createElement("div", null,
                        React.createElement(Button, { variant: "secondary", onClick: () => notify(t('تم حفظ المسودة', 'Draft saved')) }, t('حفظ مسودة', 'Save draft')),
                        tab !== 'followup' && React.createElement(Button, { onClick: () => { const i = tabs.findIndex(x => x[0] === tab); setTab(tabs[Math.min(tabs.length - 1, i + 1)][0]); } }, t('التالي', 'Next'))))),
            React.createElement("div", { className: "clinical-side" },
                React.createElement(Card, { className: "pad-16" },
                    React.createElement("h3", null, t('سياق المريض', 'Patient context')),
                    [['BP', '145/92'], ['Pulse', '82 bpm'], ['Glucose', '118 mg/dL'], ['Weight', '86 kg']].map(([a, b]) => React.createElement("div", { className: "context-metric", key: a },
                        React.createElement("span", null, a),
                        React.createElement("strong", { dir: "ltr" }, b))),
                    React.createElement(Button, { variant: "ghost", onClick: () => navigate('patientProfile') }, t('فتح ملف المريض', 'Open patient record'))),
                React.createElement(Card, { className: "pad-16" },
                    React.createElement("h3", null, t('حالة التوثيق', 'Documentation')),
                    React.createElement("div", { className: "doc-progress" },
                        React.createElement("div", { style: { width: '58%' } })),
                    React.createElement("strong", null, "58%"),
                    React.createElement("p", null, t('3 أقسام تحتاج مراجعة قبل الإكمال.', '3 sections need review before completion.'))))),
        React.createElement(Modal, { open: complete, onClose: () => setComplete(false), title: t('إكمال الزيارة', 'Complete visit'), description: t('راجع التوثيق وخطة المتابعة قبل الإكمال.', 'Review documentation and follow-up plan before completion.'), footer: React.createElement(React.Fragment, null,
                React.createElement(Button, { variant: "ghost", onClick: () => setComplete(false) }, t('إلغاء', 'Cancel')),
                React.createElement(Button, { onClick: () => { setComplete(false); notify(t('تم إكمال الزيارة وإنشاء المتابعة', 'Visit completed and follow-up created')); navigate('followups'); } }, t('تأكيد الإكمال', 'Confirm completion'))) },
            React.createElement("div", { className: "completion-checks" },
                React.createElement("div", null,
                    React.createElement(Icon, { name: "check" }),
                    React.createElement("span", null, t('تم تسجيل التشخيص', 'Diagnosis documented'))),
                React.createElement("div", null,
                    React.createElement(Icon, { name: "check" }),
                    React.createElement("span", null, t('تم تسجيل خطة العلاج', 'Treatment plan documented'))),
                React.createElement("div", { className: "warn" },
                    React.createElement(Icon, { name: "alert" }),
                    React.createElement("span", null, t('المتابعة بعد أسبوعين', 'Follow-up in two weeks'))))));
}
