import React from 'react';
import Icon from '../components/Icon.js';
import { Button, Card, Pill, StatCard } from '../components/UI.js';
import { Header } from '../components/Shell.js';
export default function Dashboard({ t, lang, setLang, theme, setTheme, navigate }) {
    const ar = lang === 'ar';
    const priorities = [
        [ar ? 'أحمد مصطفى' : 'Ahmed Mostafa', ar ? 'ينتظر منذ 22 دقيقة' : 'Waiting for 22 min', 'queue', 'bad'],
        [ar ? 'سارة عادل' : 'Sara Adel', ar ? 'جاهزة لبدء الزيارة' : 'Ready to start visit', 'queue', 'blue'],
        ['V-009818', ar ? 'التوثيق غير مكتمل' : 'Documentation incomplete', 'visits', 'warn'],
        [ar ? 'متابعة يوسف حسن' : 'Youssef follow-up', ar ? 'متأخرة يومين' : '2 days overdue', 'followups', 'bad'],
    ];
    return React.createElement("div", { className: "page-enter" },
        React.createElement(Header, { title: t('نظرة عامة', 'Dashboard'), subtitle: t('مركز تشغيل العيادة — قائمة الانتظار، الزيارات، التوثيق والمتابعات', 'Clinic operations center — queue, visits, documentation and follow-ups'), lang: lang, setLang: setLang, theme: theme, setTheme: setTheme, navigate: navigate, t: t }),
        React.createElement("div", { className: "stats-grid" },
            React.createElement(StatCard, { label: t('المرضى اليوم', 'Patients today'), value: "48", meta: t('12 مريض جديد', '12 new patients'), onClick: () => navigate('patients') }),
            React.createElement(StatCard, { label: t('في الانتظار', 'Waiting now'), value: "9", meta: t('أطول انتظار 22 دقيقة', 'Longest wait 22 min'), tone: "orange", onClick: () => navigate('queue') }),
            React.createElement(StatCard, { label: t('زيارات نشطة', 'Active visits'), value: "6", meta: t('3 غرف مشغولة', '3 rooms occupied'), tone: "indigo", onClick: () => navigate('visits') }),
            React.createElement(StatCard, { label: t('توثيق معلق', 'Pending documentation'), value: "4", meta: t('يحتاج إكمال اليوم', 'Due today'), tone: "green", onClick: () => navigate('visits') })),
        React.createElement("div", { className: "dashboard-grid top-gap" },
            React.createElement(Card, { className: "span-7 pad-20" },
                React.createElement("div", { className: "section-title" },
                    React.createElement("div", null,
                        React.createElement("h3", null, t('تدفق العيادة', 'Clinic flow')),
                        React.createElement("p", null, t('صورة لحظية لمسار المرضى من الوصول حتى الخروج', 'Live view of patient flow from check-in to exit'))),
                    React.createElement(Button, { variant: "secondary", onClick: () => navigate('queue') }, t('فتح القائمة', 'Open queue'))),
                React.createElement("div", { className: "flow-summary" }, [[t('تم الوصول', 'Checked in'), '18', 'blue'], [t('انتظار', 'Waiting'), '9', 'amber'], [t('جاهز', 'Ready'), '4', 'indigo'], [t('مع الطبيب', 'In visit'), '6', 'green']].map(([label, value, tone]) => React.createElement("button", { key: label, className: "flow-stat", onClick: () => navigate('queue') },
                    React.createElement("span", { className: `status-dot ${tone}` }),
                    React.createElement("span", null, label),
                    React.createElement("strong", null, value),
                    React.createElement(Icon, { name: "arrow", size: 15 })))),
                React.createElement("div", { className: "chart-card" },
                    React.createElement("div", { className: "chart-head" },
                        React.createElement("span", null, t('حجم الزيارات بالساعة', 'Hourly visit volume')),
                        React.createElement(Pill, { tone: "ok" }, "+12%")),
                    React.createElement("div", { className: "bar-chart" }, [38, 50, 44, 70, 58, 86, 72, 92, 76, 88, 66, 95].map((v, i) => React.createElement("div", { key: i, className: "bar-wrap" },
                        React.createElement("div", { className: "bar", style: { height: `${v}%`, animationDelay: `${i * 35}ms` } }),
                        React.createElement("span", null,
                            8 + i,
                            ":00")))))),
            React.createElement(Card, { className: "span-5 pad-20" },
                React.createElement("div", { className: "section-title" },
                    React.createElement("div", null,
                        React.createElement("h3", null, t('أولوية التشغيل', 'Operational priority')),
                        React.createElement("p", null, t('العناصر التي تحتاج تدخل الآن', 'Items needing attention now'))),
                    React.createElement(Pill, { tone: "bad" }, "4")),
                React.createElement("div", { className: "priority-list" }, priorities.map(([name, desc, target, tone]) => React.createElement("button", { key: name, className: "priority-row", onClick: () => navigate(target) },
                    React.createElement("span", { className: `priority-rail ${tone}` }),
                    React.createElement("div", null,
                        React.createElement("strong", null, name),
                        React.createElement("span", null, desc)),
                    React.createElement(Icon, { name: "arrow", size: 16 })))))),
        React.createElement("div", { className: "dashboard-grid top-gap" },
            React.createElement(Card, { className: "span-4 pad-20" },
                React.createElement("h3", null, t('عبء الأطباء', 'Doctor workload')),
                [[ar ? 'د. منى سالم' : 'Dr. Mona Salem', 4, 6], [ar ? 'د. كريم ياسين' : 'Dr. Karim Yassin', 3, 5], [ar ? 'د. هبة فؤاد' : 'Dr. Heba Fouad', 5, 6]].map(([name, current, max]) => React.createElement("div", { className: "workload-row", key: name },
                    React.createElement("div", null,
                        React.createElement("span", null, name),
                        React.createElement("strong", { dir: "ltr" },
                            current,
                            "/",
                            max)),
                    React.createElement("div", { className: "progress" },
                        React.createElement("span", { style: { width: `${current / max * 100}%` } }))))),
            React.createElement(Card, { className: "span-4 pad-20" },
                React.createElement("h3", null, t('المتابعات اليوم', 'Today follow-ups')),
                [[ar ? 'مراجعة ضغط' : 'Blood pressure review', '16:00'], [ar ? 'نتيجة تحاليل' : 'Lab result review', '17:30'], [ar ? 'مراجعة علاج' : 'Treatment review', ar ? 'غداً' : 'Tomorrow']].map(([a, b]) => React.createElement("button", { className: "compact-row", key: a, onClick: () => navigate('followups') },
                    React.createElement("span", null, a),
                    React.createElement("span", { dir: "ltr" }, b)))),
            React.createElement(Card, { className: "span-4 pad-20" },
                React.createElement("h3", null, t('آخر النشاط', 'Recent activity')),
                [['PatientCheckedIn', '10:42'], ['VisitStarted', '10:18'], ['DocumentationSaved', '10:10'], ['FollowUpCreated', '09:54']].map(([a, b]) => React.createElement("div", { className: "audit-mini", key: a },
                    React.createElement("span", { dir: "ltr" }, a),
                    React.createElement("time", null, b))))));
}
