import React from 'react';
import Icon from '../components/Icon.js';
import { Button, Pill } from '../components/UI.js';
import { ClinicLogo } from '../components/Shell.js';
export default function Login({ t, lang, setLang, theme, setTheme, navigate, platform = false }) {
    return React.createElement("div", { className: "login-page" },
        React.createElement("div", { className: "login-orb orb-a" }),
        React.createElement("div", { className: "login-orb orb-b" }),
        React.createElement("div", { className: "login-grid-bg" }),
        React.createElement("div", { className: "login-shell" },
            React.createElement("section", { className: "login-story" },
                React.createElement("div", { className: "login-brand-row" },
                    React.createElement("div", { className: "brand-mark login-mark" }, "A"),
                    React.createElement("div", null,
                        React.createElement("span", null, platform ? 'AURAN PLATFORM' : 'AURAN CLINIC'),
                        React.createElement("strong", null, platform ? t('مركز تحكم المنصة', 'Platform Control Center') : t('نظام تشغيل العيادة', 'Clinic Operating System')))),
                React.createElement("div", { className: "login-copy" },
                    React.createElement(Pill, { tone: "blue" },
                        React.createElement("span", { className: "inline-icon" },
                            React.createElement(Icon, { name: "dashboard", size: 13 }),
                            t('واجهة حية', 'Living interface'))),
                    React.createElement("h1", null, platform ? t('تحكم مركزي. حدود أمنية واضحة.', 'Central control. Clear security boundaries.') : t('كل حركة في العيادة تصبح مساراً واضحاً.', 'Every clinic action becomes a clear flow.')),
                    React.createElement("p", null, platform ? t('طبقة المنصة منفصلة عن طبقة العيادة من حيث الهوية والتوكنات والـAPIs.', 'Platform and clinic layers stay separated across identity, tokens and APIs.') : t('من وصول المريض، للانتظار، للزيارة، للتوثيق والمتابعة — النظام يتحرك مع الفريق وليس ضده.', 'From check-in to queue, visit, documentation and follow-up — the system moves with the team, not against it.'))),
                React.createElement("div", { className: "login-flow" }, ['Checked in', 'Waiting', 'Ready', 'In visit', 'Done'].map((x, i) => React.createElement(React.Fragment, { key: x },
                    React.createElement("div", { className: "login-flow-node" },
                        React.createElement("span", { style: { animationDelay: `${i * 260}ms` } }),
                        React.createElement("small", null, x)),
                    i < 4 && React.createElement("div", { className: "login-flow-line" }))))),
            React.createElement("section", { className: "login-form-side" },
                React.createElement("div", { className: "login-top-actions" },
                    React.createElement("button", { className: "icon-btn", onClick: () => setTheme(theme === 'dark' ? 'light' : 'dark') },
                        React.createElement(Icon, { name: theme === 'dark' ? 'sun' : 'moon' })),
                    React.createElement("button", { className: "lang-chip", onClick: () => setLang(lang === 'ar' ? 'en' : 'ar') },
                        React.createElement(Icon, { name: "globe", size: 15 }),
                        lang === 'ar' ? 'English' : 'العربية')),
                React.createElement(ClinicLogo, null),
                React.createElement("div", { className: "login-form-head" },
                    React.createElement("span", null, platform ? 'PLATFORM ACCESS' : 'CLINIC ACCESS'),
                    React.createElement("h2", null, platform ? t('دخول إدارة المنصة', 'Platform Admin Login') : t('مرحباً بعودتك', 'Welcome back')),
                    React.createElement("p", null, t('أكمل يومك من آخر نقطة توقفت عندها.', 'Continue your day exactly where you left off.'))),
                React.createElement("label", { className: "login-field" },
                    React.createElement("span", null, t('البريد الإلكتروني', 'Email')),
                    React.createElement("input", { defaultValue: platform ? 'platform@auran.tech' : 'doctor@auran.clinic', dir: "ltr" })),
                React.createElement("label", { className: "login-field" },
                    React.createElement("span", null, t('كلمة المرور', 'Password')),
                    React.createElement("input", { type: "password", defaultValue: "12345678", dir: "ltr" })),
                React.createElement("button", { className: "login-submit", onClick: () => navigate(platform ? 'platformClinics' : 'dashboard') },
                    React.createElement("span", null, t('دخول آمن', 'Secure sign in')),
                    React.createElement(Icon, { name: "arrow" })),
                !platform && React.createElement("button", { className: "platform-link", onClick: () => navigate('platformLogin') },
                    t('دخول Platform Admin', 'Platform Admin login'),
                    " ",
                    React.createElement(Icon, { name: "arrow", size: 14 })))));
}
