import React, { useState } from 'react';
import Icon from '../components/Icon.js';
import { Button, Card, Pill, SectionTitle } from '../components/UI.js';
import { Header } from '../components/Shell.js';
export default function PatientProfile({ t, lang, setLang, theme, setTheme, navigate, notify }) {
    const [tab, setTab] = useState('overview');
    const tabs = [['overview', 'نظرة عامة', 'Overview'], ['medical', 'الملف الطبي', 'Medical profile'], ['measurements', 'القياسات', 'Measurements'], ['visits', 'الزيارات', 'Visits'], ['orders', 'الأوامر والوصفات', 'Orders & Rx'], ['files', 'الملفات', 'Files'], ['followups', 'المتابعات', 'Follow-ups']];
    return React.createElement("div", { className: "page-enter" },
        React.createElement(Header, { title: t('أحمد مصطفى', 'Ahmed Mostafa'), subtitle: "P-10421 · 42 · 30 Sep 2026", action: React.createElement(Button, { icon: "visits", onClick: () => navigate('visits') }, t('بدء / فتح زيارة', 'Start / open visit')), lang: lang, setLang: setLang, theme: theme, setTheme: setTheme, navigate: navigate, t: t }),
        React.createElement(Card, { className: "pad-20 patient-hero" },
            React.createElement("div", { className: "patient-head" },
                React.createElement("div", { className: "avatar large" }, "AM"),
                React.createElement("div", null,
                    React.createElement("h2", null, t('أحمد مصطفى', 'Ahmed Mostafa')),
                    React.createElement("p", null, t('ذكر · 42 سنة · د. منى سالم', 'Male · 42 · Dr. Mona Salem'))),
                React.createElement("div", { className: "patient-tags" },
                    React.createElement(Pill, { tone: "bad" }, t('حساسية بنسلين', 'Penicillin allergy')),
                    React.createElement(Pill, { tone: "warn" }, t('ضغط مرتفع', 'Hypertension')))),
            React.createElement("div", { className: "tabs-row" }, tabs.map(([id, ar, en]) => React.createElement("button", { className: tab === id ? 'active' : '', key: id, onClick: () => setTab(id) }, t(ar, en))))),
        React.createElement("div", { className: "top-gap profile-grid" },
            React.createElement(Card, { className: "pad-20 profile-main" },
                tab === 'overview' && React.createElement(React.Fragment, null,
                    React.createElement(SectionTitle, { title: t('ملخص سريري', 'Clinical snapshot'), description: t('آخر بيانات مسجلة للمريض', 'Latest recorded patient data') }),
                    React.createElement("div", { className: "metric-grid" }, [[t('الضغط', 'BP'), '145/92'], [t('النبض', 'Pulse'), '82 bpm'], [t('السكر', 'Glucose'), '118 mg/dL'], [t('الوزن', 'Weight'), '86 kg']].map(([a, b]) => React.createElement("div", { className: "metric", key: a },
                        React.createElement("span", null, a),
                        React.createElement("strong", { dir: "ltr" }, b)))),
                    React.createElement(SectionTitle, { title: t('آخر الزيارات', 'Recent visits') }),
                    ['30 Sep · V-009821 · Active', '18 Sep · V-009818 · Completed', '02 Sep · V-009790 · Completed'].map(x => React.createElement("button", { className: "compact-row", key: x, onClick: () => navigate('visits') },
                        React.createElement("span", { dir: "ltr" }, x),
                        React.createElement(Icon, { name: "arrow", size: 14 })))),
                tab === 'medical' && React.createElement(React.Fragment, null,
                    React.createElement(SectionTitle, { title: t('الملف الطبي', 'Medical profile'), actions: React.createElement(Button, { variant: "secondary", icon: "edit", onClick: () => notify(t('تم فتح تعديل الملف الطبي', 'Medical profile editor opened')) }, t('تعديل', 'Edit')) }),
                    React.createElement("div", { className: "definition-grid" }, [[t('الحساسية', 'Allergies'), t('بنسلين', 'Penicillin')], [t('أمراض مزمنة', 'Chronic diseases'), t('ارتفاع ضغط الدم', 'Hypertension')], [t('تاريخ جراحي', 'Surgical history'), t('لا يوجد', 'None')], [t('تاريخ عائلي', 'Family history'), t('سكري - الأب', 'Diabetes - father')]].map(([a, b]) => React.createElement("div", { className: "definition", key: a },
                        React.createElement("span", null, a),
                        React.createElement("strong", null, b))))),
                tab === 'measurements' && React.createElement(React.Fragment, null,
                    React.createElement(SectionTitle, { title: t('القياسات', 'Measurements'), actions: React.createElement(Button, { icon: "plus", onClick: () => notify(t('تم فتح إضافة قياس', 'Add measurement opened')) }, t('إضافة قياس', 'Add measurement')) }),
                    ['30 Sep · BP 145/92 · Pulse 82', '18 Sep · BP 138/88 · Weight 86 kg', '02 Sep · Glucose 118 mg/dL'].map(x => React.createElement("div", { className: "history-row", key: x, dir: "ltr" }, x))),
                tab === 'visits' && React.createElement(React.Fragment, null,
                    React.createElement(SectionTitle, { title: t('سجل الزيارات', 'Visit history'), actions: React.createElement(Button, { onClick: () => navigate('visits') }, t('فتح صفحة الزيارات', 'Open visits')) }),
                    ['V-009821 · Active · Draft', 'V-009818 · Completed · Complete', 'V-009790 · Completed · Complete'].map(x => React.createElement("button", { className: "history-row clickable", key: x, onClick: () => navigate('clinical') },
                        React.createElement("span", { dir: "ltr" }, x),
                        React.createElement(Icon, { name: "arrow", size: 14 })))),
                tab === 'orders' && React.createElement(React.Fragment, null,
                    React.createElement(SectionTitle, { title: t('الأوامر والوصفات', 'Orders & prescriptions'), actions: React.createElement(Button, { icon: "plus", onClick: () => notify(t('تم فتح أمر جديد', 'New clinical order opened')) }, t('أمر جديد', 'New order')) }),
                    ['Amlodipine 5mg · Active', 'HbA1c · Requested', 'Chest X-Ray · Completed'].map(x => React.createElement("div", { className: "history-row", key: x, dir: "ltr" }, x))),
                tab === 'files' && React.createElement("div", { className: "empty-state" },
                    React.createElement("div", { className: "empty-icon" },
                        React.createElement(Icon, { name: "file", size: 28 })),
                    React.createElement("h3", null, t('مرفقات المريض', 'Patient attachments')),
                    React.createElement("p", null, t('ملفات المريض وملفات الزيارة مع metadata فقط في قاعدة البيانات.', 'Patient and visit files; database stores metadata only.')),
                    React.createElement(Button, { icon: "plus", onClick: () => notify(t('تم فتح رفع ملف', 'Upload opened')) }, t('رفع ملف', 'Upload file'))),
                tab === 'followups' && React.createElement(React.Fragment, null,
                    React.createElement(SectionTitle, { title: t('متابعات المريض', 'Patient follow-ups'), actions: React.createElement(Button, { onClick: () => navigate('followups') }, t('فتح المتابعات', 'Open follow-ups')) }),
                    React.createElement("div", { className: "history-row" },
                        React.createElement("span", null, t('مراجعة ضغط الدم', 'Blood pressure review')),
                        React.createElement(Pill, { tone: "blue" }, "Today · 16:00")))),
            React.createElement(Card, { className: "pad-20 profile-side" },
                React.createElement("h3", null, t('سياق المريض', 'Patient context')),
                React.createElement("div", { className: "alert-card" },
                    React.createElement(Icon, { name: "alert" }),
                    React.createElement("div", null,
                        React.createElement("strong", null, t('حساسية دوائية', 'Drug allergy')),
                        React.createElement("span", null, t('تجنب البنسلين ومشتقاته — المعلومة مدخلة بواسطة الطبيب.', 'Avoid penicillin derivatives — clinician-entered information.')))),
                React.createElement("div", { className: "context-block" },
                    React.createElement("span", null, t('الزيارة الحالية', 'Current visit')),
                    React.createElement("strong", null, "V-009821 · Active"),
                    React.createElement(Button, { variant: "ghost", onClick: () => navigate('clinical') }, t('فتح مساحة الزيارة', 'Open workspace'))))));
}
