import React, { useMemo, useState } from 'react';
import Icon from '../components/Icon.js';
import { Button, Card, Modal, Pill, Field } from '../components/UI.js';
import { Header } from '../components/Shell.js';
import { patients } from '../data.js';
export default function Patients({ t, lang, setLang, theme, setTheme, navigate, notify }) {
    const ar = lang === 'ar';
    const [query, setQuery] = useState('');
    const [open, setOpen] = useState(false);
    const filtered = useMemo(() => patients.filter(p => `${p.id} ${p.phone} ${p.ar} ${p.en}`.toLowerCase().includes(query.toLowerCase())), [query]);
    return React.createElement("div", { className: "page-enter" },
        React.createElement(Header, { title: t('المرضى', 'Patients'), subtitle: t('البحث والتسجيل والوصول للملف الطبي', 'Search, register and open the patient record'), action: React.createElement(Button, { icon: "plus", onClick: () => setOpen(true) }, t('تسجيل مريض', 'Register patient')), lang: lang, setLang: setLang, theme: theme, setTheme: setTheme, navigate: navigate, t: t }),
        React.createElement(Card, null,
            React.createElement("div", { className: "toolbar" },
                React.createElement("div", { className: "search-box" },
                    React.createElement(Icon, { name: "search", size: 17 }),
                    React.createElement("input", { value: query, onChange: e => setQuery(e.target.value), placeholder: t('ابحث بالاسم، الهاتف أو رقم الملف', 'Search by name, phone or patient number') })),
                React.createElement(Button, { variant: "secondary", icon: "filter" }, t('فلترة', 'Filters')),
                React.createElement(Pill, null,
                    filtered.length,
                    " ",
                    t('نتائج', 'results'))),
            React.createElement("div", { className: "table-wrap" },
                React.createElement("table", null,
                    React.createElement("thead", null,
                        React.createElement("tr", null,
                            React.createElement("th", null, t('المريض', 'Patient')),
                            React.createElement("th", null, t('رقم الملف', 'Patient #')),
                            React.createElement("th", null, t('الهاتف', 'Phone')),
                            React.createElement("th", null, t('الحالة', 'Condition')),
                            React.createElement("th", null, t('آخر زيارة', 'Last visit')),
                            React.createElement("th", null))),
                    React.createElement("tbody", null, filtered.map(p => React.createElement("tr", { key: p.id },
                        React.createElement("td", null,
                            React.createElement("div", { className: "person-cell" },
                                React.createElement("div", { className: "mini-avatar" }, (ar ? p.ar : p.en).split(' ').map(x => x[0]).slice(0, 2).join('')),
                                React.createElement("div", null,
                                    React.createElement("strong", null, ar ? p.ar : p.en),
                                    React.createElement("span", null,
                                        p.age,
                                        " ",
                                        t('سنة', 'years'))))),
                        React.createElement("td", { dir: "ltr" }, p.id),
                        React.createElement("td", { dir: "ltr" }, p.phone),
                        React.createElement("td", null,
                            React.createElement(Pill, { tone: "warn" }, ar ? p.conditionAr : p.conditionEn)),
                        React.createElement("td", { dir: "ltr" }, p.last),
                        React.createElement("td", null,
                            React.createElement(Button, { variant: "ghost", onClick: () => navigate('patientProfile') }, t('فتح الملف', 'Open'))))))))),
        React.createElement(Modal, { open: open, onClose: () => setOpen(false), title: t('تسجيل مريض جديد', 'Register new patient'), description: t('أدخل البيانات الأساسية. رقم المريض يتم توليده تلقائياً.', 'Enter basic details. Patient number is generated automatically.'), footer: React.createElement(React.Fragment, null,
                React.createElement(Button, { variant: "ghost", onClick: () => setOpen(false) }, t('إلغاء', 'Cancel')),
                React.createElement(Button, { onClick: () => { setOpen(false); notify(t('تم تسجيل المريض', 'Patient registered')); } }, t('حفظ', 'Save'))) },
            React.createElement("div", { className: "form-grid" },
                React.createElement(Field, { label: t('الاسم الكامل', 'Full name') },
                    React.createElement("input", null)),
                React.createElement(Field, { label: t('الهاتف', 'Phone') },
                    React.createElement("input", { dir: "ltr" })),
                React.createElement(Field, { label: t('تاريخ الميلاد', 'Date of birth') },
                    React.createElement("input", { type: "date" })),
                React.createElement(Field, { label: t('النوع', 'Gender') },
                    React.createElement("select", null,
                        React.createElement("option", null, t('ذكر', 'Male')),
                        React.createElement("option", null, t('أنثى', 'Female')))),
                React.createElement(Field, { label: t('ملاحظات', 'Notes') },
                    React.createElement("textarea", { rows: "3" })))));
}
