import React, { useState } from 'react';
import Icon from '../components/Icon.js';
import { Button, Card, EmptyState, Pill } from '../components/UI.js';
import { Header } from '../components/Shell.js';
import { reportDefinitions } from '../data.js';
export default function Reports({ t, lang, setLang, theme, setTheme, navigate, notify }) {
    const [selected, setSelected] = useState(null);
    const [preview, setPreview] = useState(false);
    const [refresh, setRefresh] = useState(0);
    const [filters, setFilters] = useState({ from: '2026-09-01', to: '2026-10-01', doctor: 'all', status: 'all' });
    return React.createElement("div", { className: "page-enter reports-page" },
        React.createElement(Header, { title: t('التقارير', 'Reports'), subtitle: t('اختر التقرير → طبّق الفلاتر → اعرض Preview → PDF / Excel / Refresh', 'Choose report → apply filters → preview → PDF / Excel / Refresh'), lang: lang, setLang: setLang, theme: theme, setTheme: setTheme, navigate: navigate, t: t }),
        React.createElement("div", { className: "reports-layout" },
            React.createElement(Card, { className: "report-list-panel pad-16" },
                React.createElement("div", { className: "section-title" },
                    React.createElement("div", null,
                        React.createElement("h3", null, t('التقارير المتاحة', 'Available reports')),
                        React.createElement("p", null, t('اختيار التقرير لا يقوم بالتصدير مباشرة', 'Selecting a report does not export immediately')))),
                React.createElement("div", { className: "report-name-list" }, reportDefinitions.map(r => React.createElement("button", { key: r.id, className: selected?.id === r.id ? 'active' : '', onClick: () => { setSelected(r); setPreview(false); } },
                    React.createElement("div", { className: "report-icon" },
                        React.createElement(Icon, { name: "reports", size: 18 })),
                    React.createElement("div", null,
                        React.createElement("strong", null, r.name),
                        React.createElement("span", null, r.description)),
                    React.createElement(Icon, { name: "arrow", size: 15 }))))),
            React.createElement("div", { className: "report-workarea" }, !selected ? React.createElement(Card, { className: "report-empty" },
                React.createElement(EmptyState, { icon: "reports", title: t('اختر تقريراً من القائمة', 'Choose a report'), description: t('بعد اختيار التقرير ستظهر فلاتره هنا، ثم يمكنك إنشاء المعاينة قبل التصدير.', 'Its filters appear here; generate a preview before exporting.') })) : React.createElement(React.Fragment, null,
                React.createElement(Card, { className: "pad-20 report-filter-card" },
                    React.createElement("div", { className: "section-title" },
                        React.createElement("div", null,
                            React.createElement("div", { className: "step-label" },
                                React.createElement("span", null, "1"),
                                t('فلترة التقرير', 'Filter report')),
                            React.createElement("h2", null, selected.name),
                            React.createElement("p", null, selected.description)),
                        React.createElement(Pill, { tone: "blue" }, t('الخطوة 1 من 2', 'Step 1 of 2'))),
                    React.createElement("div", { className: "report-filters" },
                        React.createElement("label", null,
                            React.createElement("span", null, t('من تاريخ', 'From date')),
                            React.createElement("input", { type: "date", value: filters.from, onChange: e => setFilters({ ...filters, from: e.target.value }) })),
                        React.createElement("label", null,
                            React.createElement("span", null, t('إلى تاريخ', 'To date')),
                            React.createElement("input", { type: "date", value: filters.to, onChange: e => setFilters({ ...filters, to: e.target.value }) })),
                        React.createElement("label", null,
                            React.createElement("span", null, t('الطبيب', 'Doctor')),
                            React.createElement("select", { value: filters.doctor, onChange: e => setFilters({ ...filters, doctor: e.target.value }) },
                                React.createElement("option", { value: "all" }, t('كل الأطباء', 'All doctors')),
                                React.createElement("option", null, "Dr. Mona Salem"),
                                React.createElement("option", null, "Dr. Karim Yassin"))),
                        React.createElement("label", null,
                            React.createElement("span", null, t('الحالة', 'Status')),
                            React.createElement("select", { value: filters.status, onChange: e => setFilters({ ...filters, status: e.target.value }) },
                                React.createElement("option", { value: "all" }, t('الكل', 'All')),
                                React.createElement("option", null, "Active"),
                                React.createElement("option", null, "Completed"),
                                React.createElement("option", null, "Pending")))),
                    React.createElement("div", { className: "report-filter-actions" },
                        React.createElement(Button, { variant: "ghost", onClick: () => { setFilters({ from: '2026-09-01', to: '2026-10-01', doctor: 'all', status: 'all' }); setPreview(false); } }, t('إعادة ضبط', 'Reset')),
                        React.createElement(Button, { icon: "filter", onClick: () => setPreview(true) }, t('إنشاء المعاينة', 'Generate preview')))),
                preview && React.createElement(Card, { className: "report-preview top-gap" },
                    React.createElement("div", { className: "report-preview-head" },
                        React.createElement("div", null,
                            React.createElement("div", { className: "step-label" },
                                React.createElement("span", null, "2"),
                                t('معاينة التقرير', 'Report preview')),
                            React.createElement("h3", null, selected.name),
                            React.createElement("p", null,
                                t('آخر تحديث', 'Last refresh'),
                                " 10:",
                                42 + refresh)),
                        React.createElement("div", { className: "preview-actions" },
                            React.createElement(Button, { variant: "ghost", icon: "refresh", onClick: () => { setRefresh(v => v + 1); notify(t('تم تحديث المعاينة', 'Preview refreshed')); } }, t('تحديث', 'Refresh')),
                            React.createElement(Button, { variant: "secondary", icon: "pdf", onClick: () => notify(t('تم إنشاء PDF', 'PDF generated')) }, "PDF"),
                            React.createElement(Button, { variant: "secondary", icon: "excel", onClick: () => notify(t('تم إنشاء Excel', 'Excel generated')) }, "Excel"))),
                    React.createElement("div", { className: "report-summary-strip" },
                        React.createElement("div", null,
                            React.createElement("span", null, t('النتائج', 'Results')),
                            React.createElement("strong", null, "143")),
                        React.createElement("div", null,
                            React.createElement("span", null, t('الفترة', 'Period')),
                            React.createElement("strong", { dir: "ltr" }, "01 Sep — 01 Oct")),
                        React.createElement("div", null,
                            React.createElement("span", null, t('الطبيب', 'Doctor')),
                            React.createElement("strong", null, filters.doctor === 'all' ? t('كل الأطباء', 'All doctors') : filters.doctor))),
                    React.createElement("div", { className: "table-wrap" },
                        React.createElement("table", null,
                            React.createElement("thead", null,
                                React.createElement("tr", null,
                                    React.createElement("th", null, "#"),
                                    React.createElement("th", null, t('المريض', 'Patient')),
                                    React.createElement("th", null, t('التاريخ', 'Date')),
                                    React.createElement("th", null, t('الطبيب', 'Doctor')),
                                    React.createElement("th", null, t('الحالة', 'Status')))),
                            React.createElement("tbody", null, [['001', t('أحمد مصطفى', 'Ahmed Mostafa'), '30 Sep 2026', t('د. منى', 'Dr. Mona'), 'Completed'], ['002', t('سارة عادل', 'Sara Adel'), '29 Sep 2026', t('د. هبة', 'Dr. Heba'), 'Completed'], ['003', t('يوسف حسن', 'Youssef Hassan'), '27 Sep 2026', t('د. كريم', 'Dr. Karim'), 'Pending'], ['004', t('نور كمال', 'Nour Kamal'), '26 Sep 2026', t('د. كريم', 'Dr. Karim'), 'Active']].map(r => React.createElement("tr", { key: r[0] }, r.map((x, i) => React.createElement("td", { key: i, dir: i === 0 || i === 2 ? 'ltr' : undefined }, i === 4 ? React.createElement(Pill, { tone: x === 'Pending' ? 'warn' : x === 'Active' ? 'blue' : 'ok' }, x) : x))))))),
                    React.createElement("div", { className: "report-preview-foot" },
                        React.createElement("span", null, t('4 صفوف للمعاينة فقط · التصدير يستخدم كامل النتائج', '4 preview rows only · export uses the full result set')),
                        React.createElement("span", null,
                            t('صلاحية التصدير', 'Export permission'),
                            ": ",
                            React.createElement("code", null, "Reports_Export"))))))));
}
