import React,{useState} from 'react';
import Icon from '../components/Icon.js';
import {Button,Card,Field,Pill,Toggle} from '../components/UI.js';
import {Header} from '../components/Shell.js';
import {countersSeed,medicalFieldsSeed,measurementTypesSeed,transitionSeed,workflowSeed} from '../data.js';

const tabs=[
  ['general','dashboard','عام','General'],['workflow','queue','مسار العمل','Workflow'],['medical','file','حقول الملف الطبي','Medical fields'],['measurements','measure','أنواع القياسات','Measurement types'],['counters','numbers','العدادات','Counters'],['security','lock','الأمان والجلسات','Security & sessions'],['branding','palette','هوية العيادة','Clinic branding']
];

export default function Settings({t,lang,setLang,theme,setTheme,navigate,notify}){
  const[tab,setTab]=useState('general');
  const[flow,setFlow]=useState(workflowSeed);
  const[fields,setFields]=useState(medicalFieldsSeed);
  const[drag,setDrag]=useState(null);
  const[rotation,setRotation]=useState(true);
  const[invalidate,setInvalidate]=useState(true);
  const[rate,setRate]=useState(true);
  const[accent,setAccent]=useState('#3B82F6');
  const move=(list,setList,to)=>{if(drag===null)return;const n=[...list];const[x]=n.splice(drag,1);n.splice(to,0,x);setList(n);setDrag(null)};
  const saved=()=>notify(t('تم حفظ الإعدادات','Settings saved'));

  const general=<div className="settings-two-col">
    <Card className="pad-20"><h3>{t('هوية العيادة','Clinic identity')}</h3><div className="form-stack"><Field label={t('اسم العيادة','Clinic name')}><input defaultValue="AURAN Demo Clinic"/></Field><Field label={t('كود العيادة','Clinic code')}><input defaultValue="AUR-DEMO" dir="ltr"/></Field><Field label={t('المنطقة الزمنية','Timezone')}><select defaultValue="Africa/Cairo"><option>Africa/Cairo</option><option>Asia/Riyadh</option><option>Asia/Dubai</option></select></Field></div></Card>
    <Card className="pad-20"><h3>{t('التفضيلات','Defaults')}</h3><div className="form-stack"><Field label={t('اللغة الافتراضية','Default language')}><select defaultValue="ar"><option value="ar">العربية — RTL</option><option value="en">English — LTR</option></select></Field><Field label={t('تنسيق التاريخ','Date format')}><select defaultValue="dd"><option value="dd">DD MMM YYYY</option><option value="iso">YYYY-MM-DD</option></select></Field><Button onClick={saved}>{t('حفظ','Save')}</Button></div></Card>
  </div>;

  const workflow=<><Card className="workflow-canvas pad-20"><div className="section-title"><div><h3>{t('المسار الرئيسي','Primary workflow')}</h3><p>{t('الحالات مرتبطة ببعضها. اسحب لتغيير الترتيب.','Connected states. Drag to reorder.')}</p></div><Button icon="plus" onClick={()=>notify(t('فتح إضافة حالة','Add state opened'))}>{t('إضافة حالة','Add state')}</Button></div><div className="workflow-nodes">{flow.map((s,i)=><React.Fragment key={s.id}><article className={`workflow-node tone-${s.color}`} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>move(flow,setFlow,i)}><div className="workflow-node-top"><Icon name="drag" size={15}/><button className="icon-btn" onClick={()=>notify(t('فتح تعديل الحالة','Edit state opened'))}><Icon name="edit" size={14}/></button></div><span className={`status-dot ${s.color}`}/><strong dir="ltr">{s.name}</strong>{s.system&&<Pill tone="warn">System</Pill>}</article>{i<flow.length-1&&<div className="workflow-connector"><span/><Icon name="arrow" size={15}/></div>}</React.Fragment>)}</div></Card><Card className="pad-20 top-gap"><div className="section-title"><div><h3>{t('قواعد الانتقال','Transition rules')}</h3><p>From → To + Permission</p></div><Button variant="secondary" icon="plus" onClick={()=>notify(t('فتح إضافة انتقال','Add transition opened'))}>{t('إضافة انتقال','Add transition')}</Button></div>{transitionSeed.map((x,i)=><div className="transition-row" key={i}><strong dir="ltr">{x.from}</strong><Icon name="arrow" size={16}/><strong dir="ltr">{x.to}</strong><Pill>{x.permission}</Pill><Toggle checked={x.enabled} onChange={()=>{}}/><button className="icon-btn" onClick={()=>notify(t('فتح تعديل الانتقال','Edit transition opened'))}><Icon name="edit" size={15}/></button></div>)}</Card></>;

  const medical=<Card><div className="section-title pad-20"><div><h3>{t('حقول الملف الطبي','Medical Profile Fields')}</h3><p>{t('إضافة وتعديل وترتيب الحقول الديناميكية.','Add, edit and reorder dynamic fields.')}</p></div><Button icon="plus" onClick={()=>notify(t('فتح إضافة حقل','Add field opened'))}>{t('حقل جديد','New field')}</Button></div><div className="table-wrap"><table><thead><tr><th>#</th><th>{t('الاسم','Name')}</th><th>{t('النوع','Type')}</th><th>{t('إجباري','Required')}</th><th>{t('الحالة','Status')}</th><th/></tr></thead><tbody>{fields.map((f,i)=><tr key={f.id} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>move(fields,setFields,i)}><td><Icon name="drag" size={15}/> {i+1}</td><td><strong>{f.name}</strong></td><td><Pill>{f.type}</Pill></td><td>{f.required?t('نعم','Yes'):t('لا','No')}</td><td><Pill tone={f.active?'ok':'bad'}>{f.active?'Active':'Disabled'}</Pill></td><td><Button variant="ghost" icon="edit" onClick={()=>notify(t('فتح تعديل الحقل','Edit field opened'))}>{t('تعديل','Edit')}</Button></td></tr>)}</tbody></table></div></Card>;

  const measurements=<div className="measurement-grid">{measurementTypesSeed.map(m=><Card className="measurement-card pad-20" key={m.code}><div className="measurement-head"><div className="measurement-icon"><Icon name="measure"/></div><Pill tone={m.active?'ok':'bad'}>{m.active?'Active':'Disabled'}</Pill></div><h3>{m.name}</h3><code>{m.code}</code><div className="measurement-meta"><span>{t('الوحدة','Unit')} <strong>{m.unit}</strong></span><span>{t('نوع القيمة','Value type')} <strong>{m.valueType}</strong></span></div><Button variant="ghost" icon="edit" onClick={()=>notify(t('فتح تعديل نوع القياس','Edit measurement opened'))}>{t('تعديل','Edit')}</Button></Card>)}</div>;

  const counters=<div className="counter-grid">{countersSeed.map(c=><Card className="counter-card pad-20" key={c.name}><div className="counter-head"><h3>{c.name}</h3><Button variant="ghost" icon="edit" onClick={()=>notify(t('فتح تعديل العداد','Edit counter opened'))}>{t('تعديل','Edit')}</Button></div><div className="counter-preview"><span>{t('القيمة التالية','Next value')}</span><strong dir="ltr">{`${c.prefix}${String(c.next).padStart(c.padding,'0')}`}</strong><div className="counter-meta"><span>Prefix <code>{c.prefix}</code></span><span>Padding <code>{c.padding}</code></span><span>{t('القيمة الخام','Raw next')} <code>{c.next}</code></span></div></div></Card>)}</div>;

  const security=<div className="settings-two-col"><Card className="pad-20"><h3>{t('الجلسات','Sessions')}</h3><div className="form-stack"><Field label={t('مدة الجلسة بالساعات','Session duration in hours')}><input type="number" defaultValue={8}/></Field><div className="setting-switch-row"><div><strong>Refresh Token Rotation</strong><span>{t('منع replay وإعادة استخدام التوكن.','Prevent replay and token reuse.')}</span></div><Toggle checked={rotation} onChange={setRotation}/></div><div className="setting-switch-row"><div><strong>{t('إلغاء الجلسات بعد تغيير الدور/الحالة','Invalidate sessions on role/status change')}</strong><span>{t('التغييرات الأمنية تطبق فوراً.','Security changes apply immediately.')}</span></div><Toggle checked={invalidate} onChange={setInvalidate}/></div></div></Card><Card className="pad-20"><h3>{t('حماية الدخول','Login protection')}</h3><div className="setting-switch-row"><div><strong>{t('تحديد معدل تسجيل الدخول','Login rate limiting')}</strong><span>{t('تقليل المحاولات المتكررة.','Reduce repeated attempts.')}</span></div><Toggle checked={rate} onChange={setRate}/></div><div className="setting-switch-row protected"><div><strong>{t('حماية آخر Super User','Protect last active Super User')}</strong><span>{t('حماية أساسية لا يمكن إيقافها.','Core safeguard cannot be disabled.')}</span></div><Toggle checked={true} disabled/></div><Button onClick={saved}>{t('حفظ','Save')}</Button></Card></div>;

  const branding=<div className="branding-layout"><Card className="pad-20"><h3>{t('التخصيص','Customization')}</h3><Field label={t('اللون الأساسي','Accent color')}><input type="color" value={accent} onChange={e=>setAccent(e.target.value)}/></Field><div className="form-stack top-gap"><Field label={t('اسم العرض','Display name')}><input defaultValue="AURAN Demo Clinic"/></Field><Button onClick={saved}>{t('حفظ','Save')}</Button></div></Card><Card className="pad-20"><h3>{t('معاينة','Preview')}</h3><div className="brand-preview" style={{'--preview-accent':accent}}><div className="brand-preview-logo">A</div><strong>AURAN Clinic</strong><span>{t('هوية العيادة فوق نظام AURAN','Clinic identity on top of AURAN system')}</span></div></Card></div>;

  const body={general,workflow,medical,measurements,counters,security,branding}[tab];
  const active=tabs.find(x=>x[0]===tab);
  return <div className="page-enter"><Header title={t('الإعدادات','Settings')} subtitle={t('الإعدادات العامة والتكوين التشغيلي والأمان في مركز واحد.','General settings, operational configuration and security in one hub.')} lang={lang} setLang={setLang} theme={theme} setTheme={setTheme} navigate={navigate} t={t}/><div className="settings-layout"><Card className="settings-nav pad-12"><div className="settings-nav-title"><strong>{t('الأقسام','Sections')}</strong><span>{t('كل التكوين في مكان واحد','All configuration in one place')}</span></div>{tabs.map(([id,icon,a,e])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span className="settings-nav-icon"><Icon name={icon} size={18}/></span><div><strong>{t(a,e)}</strong><span>{id==='workflow'?t('الحالات والانتقالات','States & transitions'):id==='medical'?t('الحقول الديناميكية','Dynamic fields'):id==='measurements'?t('الوحدات والقيم','Units & values'):id==='counters'?t('الصيغ والتسلسل','Formats & sequence'):id==='security'?t('الجلسات والحماية','Sessions & safeguards'):id==='branding'?t('التخصيص والمعاينة','Customization & preview'):t('الهوية والمنطقة الزمنية','Identity & timezone')}</span></div><Icon name="arrow" size={14}/></button>)}</Card><main className="settings-content"><div className="settings-content-head"><div><span className="section-eyebrow">{t(active[2],active[3])}</span><h2>{t(active[2],active[3])}</h2><p>{t('يمكن تعديل كل الإعدادات من نفس المركز.','All settings are editable from this hub.')}</p></div></div>{body}</main></div></div>;
}
